name: dartotsu_extension_bridge
description: "A new Flutter plugin project."
version: 0.0.6
homepage:
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.4.0
  flutter_device_apps: ^0.3.1
  install_plugin: ^2.1.0
  isar_community: ^3.3.0-dev.2
  isar_community_flutter_libs: ^3.3.0-dev.2
  d4rt: ^0.1.7
  get: ^4.7.2
  path_provider: ^2.1.5
  path: ^1.9.1
  http_interceptor: ^2.0.0
  html: ^0.15.6
  intl: ^0.20.2
  flutter_inappwebview: ^6.2.0-beta.2
  pseudom: ^1.0.1
  encrypt: ^5.0.3
  xpath_selector_html_parser: ^3.0.1
  js_packer: ^0.0.6
  crypto: ^3.0.6
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: f3cef51

  epubx:
    git:
      url: https://github.com/kodjodevf/epubx.dart.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.0-dev.2
  build_runner: ^2.5.4
  path_provider_platform_interface: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.aayush262.dartotsu_extension_bridge
        pluginClass: DartotsuExtensionBridgePlugin
      ios:
        pluginClass: DartotsuExtensionBridgePlugin
      linux:
        pluginClass: DartotsuExtensionBridgePlugin
      macos:
        pluginClass: DartotsuExtensionBridgePlugin
      windows:
        pluginClass: DartotsuExtensionBridgePluginCApi

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
